version: "2"
services:
  mysql:
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_ROOT_HOST: "172.25.0.1"
      MYSQL_ROOT_PASSWORD: "root"
      MYSQL_DATABASE: "blog"
    volumes:
      - "mysql:/var/lib/mysql"
    ports:
      - "43309:3306"

volumes:
  mysql: {}


networks:
  default:
    driver: bridge
    ipam:
     config:
       - subnet: 172.25.0.0/24
         gateway: 172.25.0.1
