version: "2"

services:
  postgres:
    image: postgres:11.1
    restart: always
    environment:
      POSTGRES_PASSWORD: "root"
      POSTGRES_USER: "root"
      POSTGRES_DB: "blog"
    volumes:
      - "postgres:/var/lib/postgresql/data"
    ports:
      - "15432:5432"


volumes:
  mysql: {}
  postgres: {}