version: "2"
services:
  redis:
    image: redis:4-alpine
    restart: always
    volumes:
      - "./redis.conf:/usr/local/etc/redis/redis.conf"
      - "redis:/data"
    ports:
      - "6019:6379"


volumes:
  redis: {}


networks:
  default:
    driver: bridge
    ipam:
     config:
       - subnet: 172.25.0.0/24
         gateway: 172.25.0.1
