apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: thebookofjoel
  namespace: thebookofjoel
spec:
  template:
    metadata:
      labels:
        name: thebookofjoel-main
    spec:
      containers:
        - name: backend
          image: backend
          ports:
            - containerPort: 8000
          env:
            - name: DEPLOYED
              value: "True"
            - name: DB_HOST
              valueFrom:
                secretKeyRef:
                  name: db-host
                  key: db-host
            - name: DB_PORT
              valueFrom:
                secretKeyRef:
                  name: db-port
                  key: db-port
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: db-password
                  key: db-password
        - name: nginx
          image: nginx
          ports:
            - containerPort: 80
