apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: ingress
  namespace: thebookofjoel
  annotations:
    kubernetes.io/ingress.class: traefik
spec:
  rules:
  - host: k3stest.thebookofjoel.com
    http:
      paths:
        - path: /api
          backend:
            serviceName: thebookofjoel-backend
            servicePort: 80
        - path: /admin
          backend:
            serviceName: thebookofjoel-backend
            servicePort: 80
        - path: /
          backend:
            serviceName: thebookofjoel-nginx
            servicePort: 80
